name: CI

on: [push, pull_request]

jobs:
  build-dev-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Docker Buildx
      uses: crazy-max/ghaction-docker-buildx@v1.4.0
      with:
        version: v0.3.1
    - name: Configuring nodejs 10.x version
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: login/yarn build
      run: |
        docker login -u "${{ secrets.QUAY_USERNAME }}" -p "${{ secrets.QUAY_PASSWORD }}" quay.io
        echo "run yarn without post install scripts"
        df -h
        yarn install --ignore-scripts
        sudo apt clean
        docker image prune -a -f
        df -h
    - name: theia-dev images build
      run: |
        echo "Building theia-dev image"
        cd dockerfiles/theia-dev
        ./build.sh --dockerfile:Dockerfile.alpine --skip-tests --dry-run --organization:quay.io/fbenoit --tag:buildx
        cat .Dockerfile
        IMAGE_FULL="quay.io/fbenoit/che-theia-dev:buildx"
        docker buildx build --cache-from=type=registry,ref=${IMAGE_FULL}--cache-to=type=registry,ref=${IMAGE_FULL},mode=max --platform linux/amd64,linux/arm64,linux/ppc64le,linux/s390x -t "${IMAGE_FULL}" --push --file ./.Dockerfile .
  build-image:
    runs-on: ubuntu-latest
    needs: build-dev-image
    steps:
    - uses: actions/checkout@v2
    - name: Docker Buildx
      uses: crazy-max/ghaction-docker-buildx@v1.4.0
      with:
        version: v0.3.1
    - name: login
      run: |
        docker login -u "${{ secrets.QUAY_USERNAME }}" -p "${{ secrets.QUAY_PASSWORD }}" quay.io
        df -h
        sudo apt clean
        docker image prune -a -f
        df -h
    - name: theia images build
      run: |
        echo "Building theia image"
        cd dockerfiles/theia
        ./build.sh --dockerfile:Dockerfile.alpine --skip-tests --dry-run --organization:quay.io/fbenoit --tag:buildx --target:runtime --build-args:DO_REMOTE_CHECK=false --branch:master --git-ref:"refs\\/heads\\/master"
        cat .Dockerfile
        docker buildx build --platform linux/amd64,linux/arm64,linux/ppc64le,linux/s390x -t "quay.io/fbenoit/che-theia:buildx" --push --file ./.Dockerfile . 
