name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      name: Configuring nodejs 10.x version
      with:
        node-version: '10.x'    
    - name: Docker Buildx
      uses: crazy-max/ghaction-docker-buildx@v1.4.0
      with:
        version: latest
    - name: Build
      run: |
        docker login -u "${QUAY_USERNAME}" -p "${QUAY_PASSWORD}" quay.io
        
        docker buildx build --platform linux/amd64,linux/arm64,linux/ppc64le,linux/s390x,linux/386,linux/arm/v7,linux/arm/v6 -t "quay.io/fbenoit/che-plugin-registry" --push --file ./build/dockerfiles/Dockerfile --target registry . 
        docker images
      env:
        QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}
        QUAY_PASSWORD: ${{ secrets.QUAY_PASSWORD }}      
