name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Docker Buildx
      uses: crazy-max/ghaction-docker-buildx@v1.4.0
      with:
        # Buildx version. Example: v0.3.0
        version: latest
    - name: login/yarn build
      run: |
        docker login -u "${QUAY_USERNAME}" -p "${QUAY_PASSWORD}" quay.io
        echo "run yarn without post install scripts"
        yarn install --ignore-scripts
      env:
        QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}
        QUAY_PASSWORD: ${{ secrets.QUAY_PASSWORD }}
    - name: theia images build
      run: |
        echo "Building theia-dev image"
        export CURRENT_DIR=$(pwd)
        cd ${CURRENT_DIR}/dockerfiles/theia-dev
        ./build.sh --dockerfile:Dockerfile.alpine --skip-tests --dry-run --organization:quay.io/fbenoit --tag:buildx
        docker buildx build --platform linux/amd64,linux/arm/v7 -t "quay.io/fbenoit/che-theia-dev:buildx" --push --file ./.Dockerfile . 
        echo "Building theia image"
        cd ${CURRENT_DIR}/dockerfiles/theia
        ./build.sh --dockerfile:Dockerfile.alpine --skip-tests --dry-run --organization:quay.io/fbenoit --tag:buildx --target:runtime
        docker buildx build --platform linux/amd64,linux/arm/v7 -t "quay.io/fbenoit/che-theia:buildx" --push --file ./.Dockerfile . 
